language: c

script: cmake --version && cmake . && make VERBOSE=1
sudo: false
addons:
  apt:
    sources:
      - ppa:smspillaz/cmake-3.0.2
    packages:
      - python-yaml
      - libtinfo-dev
      - cmake
compiler:
  - gcc
    #- clang

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fccf07549cf55d00de5d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
