language: c
script: make V=1
sudo: false
addons:
  apt:
    packages:
      - python-yaml
      - ninja-build
      - libtinfo-dev
compiler:
  - gcc
    #- clang

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fccf07549cf55d00de5d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
